services:

  # web:
  #   build:
  #     context: .
  #     dockerfile: docker/nginx/Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     - frontend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa0000
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pg-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - pg-network

  backend:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./apps/backend:/backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - pg-network

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./apps/frontend:/frontend
      - ./apps/frontend/node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

volumes:
  pg-data:

networks:
  pg-network:
    driver: bridge