services:

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./apps/backend:/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sa:sa0000@db:5432/fastapi_db
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./apps/frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa0000
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: