services:

  # web:
  #   build:
  #     context: .
  #     dockerfile: docker/nginx/Dockerfile
  #   ports:
  #     - "${WEB_PORT}:${WEB_DEFAULT_PORT}"
  #   depends_on:
  #     - backend
  #     - frontend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${POSTGRES_DEFAULT_PORT}"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/pgdata:/var/lib/postgresql/data
    networks:
      - pg-network

  backend:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./apps/backend:/backend
    ports:
      - "${BACKEND_PORT}:${FASTAPI_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - pg-network

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./apps/frontend:/frontend
      - ./apps/frontend/node_modules:/frontend/node_modules
    ports:
      - "${FRONTEND_PORT}:${VITE_PORT}"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

volumes:
  pg-data:

networks:
  pg-network:
    driver: bridge